name: Deploy lolink-front

on:
  pull_request:
    branches:
      - staging
    paths:
      - lolink_front*/**
    types:
      - closed

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Set env
        run: |
          cd lolink_front &&
          touch .env.development &&
          echo "${{ secrets.DEV_SERVER_ENV }}" >> .env.development

      - name: Build
        run: |
          cd lolink_front &&
          yarn build:dev

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Show current working directory
        run: pwd
      - name: List directory contents
        run: ls -al

      - name: Deploy to S3
        env:
          AWS_S3_BUCKET: "dev.lolink.xyz" # 버킷 이름
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
        run: |
          aws s3 sync .next s3://dev.lolink.xyz
